"""OLM body normalization for signatures, reply headers, disclaimers, and multilingual mail."""

from __future__ import annotations

import time

from mailarium.parse_olm import (
    Email,
)
from mailarium.parse_olm_normalization import (
    BODY_NORMALIZATION_VERSION,
    _has_newsletter_hint,
    _has_normalized_quoted_separator,
    _has_sent_from_footer,
    _is_normalized_quoted_separator,
    _is_normalized_reply_header_line,
    _is_outlook_separator_line,
    _normalized_body_noise_score,
)


def _email_with_body(*, body_text, body_html=""):
    """Create a minimal inbox email for body-normalization cases."""
    return Email(
        message_id="<m@test>",
        subject="Test",
        sender_name="",
        sender_email="",
        to=[],
        cc=[],
        bcc=[],
        date="",
        body_text=body_text,
        body_html=body_html,
        folder="Inbox",
        has_attachments=False,
    )


def test_normalization_line_parsers_preserve_regex_parity() -> None:
    assert _is_normalized_reply_header_line("From: Alice")
    assert _is_normalized_reply_header_line("Envoyée: vendredi")
    assert _is_normalized_reply_header_line("Wysłano: poniedziałek")
    assert not _is_normalized_reply_header_line("From:")
    assert _is_normalized_quoted_separator("----- Original Message -----")
    assert _is_normalized_quoted_separator("-- Ursprüngliche Nachricht")
    assert _has_normalized_quoted_separator("Lead\n-- Forwarded message --\nBody")
    assert _is_outlook_separator_line("__________")
    assert not _is_outlook_separator_line("_________")
    assert _has_sent_from_footer("Body\nSent from my iPhone")
    assert _has_newsletter_hint("To stop these messages, unsubscribe here.")


def test_normalization_line_parsers_are_linear_on_adversarial_input() -> None:
    adversarial = ("From-not-a-header " * 20_000) + "\n" + ("_-" * 50_000)
    started = time.perf_counter()
    _normalized_body_noise_score(adversarial)
    assert time.perf_counter() - started < 1.0


# ── Email.uid fallback (lines 98-99) ─────────────────────────


# ── Clean body HTML ─────────────────────────────────────────────


class TestCleanBodyHtml:
    def test_clean_body_html_in_body_text_field(self):
        """When body_text contains HTML, clean_body strips HTML tags."""
        email = _email_with_body(body_text="<html><body><p>Hello</p></body></html>")
        result = email.clean_body
        assert "Hello" in result
        assert "<html>" not in result
        assert "<p>" not in result

    def test_clean_body_prefers_cleaner_html_representation(self):
        """Noisy autogenerated plain text should not always beat cleaner HTML."""
        email = Email(
            message_id="<m@test>",
            subject="Test",
            sender_name="",
            sender_email="",
            to=[],
            cc=[],
            bcc=[],
            date="",
            body_text=(
                "Visible summary.\n\n"
                "From: Alice <employee@example.test>\n"
                "Sent: Monday, January 1, 2025 10:00 AM\n"
                "To: Bob <bob@example.com>\n"
                "Subject: RE: Test\n\n"
                "> Prior content"
            ),
            body_html="<div><p>Visible summary.</p></div>",
            folder="Inbox",
            has_attachments=False,
        )
        assert email.clean_body == "Visible summary."
        assert email.clean_body_source == "body_html"
        assert email.body_normalization_version == BODY_NORMALIZATION_VERSION

    def test_clean_body_tracks_html_in_body_text_source(self):
        email = _email_with_body(body_text="<html><body><p>Hello</p></body></html>")
        assert email.clean_body == "Hello"
        assert email.clean_body_source == "body_text_html"


# ── Signatures and footers ──────────────────────────────────────


class TestCleanBodySignatures:
    def test_clean_body_strips_mobile_signature_in_normalized_body(self):
        email = Email(
            message_id="<m@test>",
            subject="Test",
            sender_name="",
            sender_email="",
            to=[],
            cc=[],
            bcc=[],
            date="",
            body_text="See you tomorrow.\n\nSent from my iPhone",
            body_html="",
            folder="Inbox",
            has_attachments=False,
        )
        assert email.clean_body == "See you tomorrow."
        assert email.clean_body_source == "body_text"
        assert email.body_normalization_version == BODY_NORMALIZATION_VERSION

    def test_clean_body_strips_closing_signature_in_normalized_body(self):
        email = Email(
            message_id="<m@test>",
            subject="Test",
            sender_name="",
            sender_email="",
            to=[],
            cc=[],
            bcc=[],
            date="",
            body_text="I'll handle it.\n\nBest regards,\nAlice Smith\nManager",
            body_html="",
            folder="Inbox",
            has_attachments=False,
        )
        assert email.clean_body == "I'll handle it."

    def test_clean_body_keeps_regular_prose_without_signature_marker(self):
        email = Email(
            message_id="<m@test>",
            subject="Test",
            sender_name="",
            sender_email="",
            to=[],
            cc=[],
            bcc=[],
            date="",
            body_text="Just a regular email without a signature.",
            body_html="",
            folder="Inbox",
            has_attachments=False,
        )
        assert email.clean_body == "Just a regular email without a signature."

    def test_clean_body_strips_get_outlook_ios_footer_in_normalized_body(self):
        email = Email(
            message_id="<m@test>",
            subject="Test",
            sender_name="",
            sender_email="",
            to=[],
            cc=[],
            bcc=[],
            date="",
            body_text="Please see the attached file.\n\nGet Outlook for iOS",
            body_html="",
            folder="Inbox",
            has_attachments=False,
        )
        assert email.clean_body == "Please see the attached file."
        assert email.body_normalization_version == BODY_NORMALIZATION_VERSION


# ── Legal disclaimers ──────────────────────────────────────────


class TestCleanBodyLegalDisclaimers:
    def test_clean_body_strips_multiline_legal_disclaimer_tail(self):
        email = Email(
            message_id="<m@test>",
            subject="Test",
            sender_name="",
            sender_email="",
            to=[],
            cc=[],
            bcc=[],
            date="",
            body_text=(
                "Action items are attached.\n\n"
                "This email and any attachments are confidential and intended only for the named recipient.\n"
                "If you are not the intended recipient, please notify the sender and delete this email.\n"
                "Any unauthorized review, use, disclosure, or distribution is prohibited."
            ),
            body_html="",
            folder="Inbox",
            has_attachments=False,
        )
        assert email.clean_body == "Action items are attached."
        assert email.body_normalization_version == BODY_NORMALIZATION_VERSION

    def test_clean_body_keeps_single_line_confidentiality_notice(self):
        email = Email(
            message_id="<m@test>",
            subject="Test",
            sender_name="",
            sender_email="",
            to=[],
            cc=[],
            bcc=[],
            date="",
            body_text=("Status report attached.\n\nConfidentiality notice: This email may contain privileged information."),
            body_html="",
            folder="Inbox",
            has_attachments=False,
        )
        assert "Confidentiality notice" in email.clean_body


# ── English reply / forward header stripping ──────────────────


class TestCleanBodyEnglishReplyHeaders:
    def test_clean_body_strips_reply_quote_tail_before_persistence(self):
        email = Email(
            message_id="<m@test>",
            subject="RE: Project update",
            sender_name="",
            sender_email="",
            to=[],
            cc=[],
            bcc=[],
            date="",
            body_text=(
                "Latest status is below.\n\n----- Original Message -----\nFrom: Alice\nSubject: Project update\n\nPrior body."
            ),
            body_html="",
            folder="Inbox",
            has_attachments=False,
        )
        assert email.email_type == "reply"
        assert email.clean_body == "Latest status is below."
        assert email.body_normalization_version == BODY_NORMALIZATION_VERSION

    def test_clean_body_keeps_separator_text_for_original_email(self):
        email = Email(
            message_id="<m@test>",
            subject="Project archive note",
            sender_name="",
            sender_email="",
            to=[],
            cc=[],
            bcc=[],
            date="",
            body_text=("Reference below.\n\n----- Original Message -----\nThis separator is part of the saved note."),
            body_html="",
            folder="Inbox",
            has_attachments=False,
        )
        assert email.email_type == "original"
        assert "----- Original Message -----" in email.clean_body

    def test_clean_body_strips_reply_header_only_tail_before_persistence(self):
        email = Email(
            message_id="<m@test>",
            subject="RE: Status",
            sender_name="",
            sender_email="",
            to=[],
            cc=[],
            bcc=[],
            date="",
            body_text=(
                "Latest answer.\n\n"
                "From: Alice <employee@example.test>\n"
                "Sent: Monday, January 1, 2025 10:00 AM\n"
                "To: Bob <bob@example.com>\n"
                "Subject: Status"
            ),
            body_html="",
            folder="Inbox",
            has_attachments=False,
        )
        assert email.email_type == "reply"
        assert email.clean_body == "Latest answer."
        assert email.body_normalization_version == BODY_NORMALIZATION_VERSION

    def test_clean_body_strips_reply_header_block_after_intro_before_persistence(self):
        email = Email(
            message_id="<m@test>",
            subject="FW: Status",
            sender_name="",
            sender_email="",
            to=[],
            cc=[],
            bcc=[],
            date="",
            body_text=(
                "Please see below.\n\n"
                "From: Alice <employee@example.test>\n"
                "Sent: Monday, January 1, 2025 10:00 AM\n"
                "To: Bob <bob@example.com>\n"
                "Subject: Status\n\n"
                "Prior body content."
            ),
            body_html="",
            folder="Inbox",
            has_attachments=False,
        )
        assert email.email_type == "forward"
        assert email.clean_body == "Please see below."

    def test_clean_body_strips_html_reply_header_block_after_intro(self):
        email = Email(
            message_id="<m@test>",
            subject="AW: Status",
            sender_name="",
            sender_email="",
            to=[],
            cc=[],
            bcc=[],
            date="",
            body_text="",
            body_html=(
                "<div>Aktueller Stand unten.</div>"
                "<div><br></div>"
                "<div>Von: Alice &lt;employee@example.test&gt;</div>"
                "<div>Gesendet: Montag, 1. Januar 2025 10:00</div>"
                "<div>An: Bob &lt;bob@example.com&gt;</div>"
                "<div>Betreff: Status</div>"
                "<div><br></div>"
                "<div>Vorheriger Inhalt.</div>"
            ),
            folder="Inbox",
            has_attachments=False,
        )
        assert email.email_type == "reply"
        assert email.clean_body == "Aktueller Stand unten."
        assert email.clean_body_source == "body_html"

    def test_clean_body_keeps_headerish_tail_for_original_email(self):
        email = Email(
            message_id="<m@test>",
            subject="Archive note",
            sender_name="",
            sender_email="",
            to=[],
            cc=[],
            bcc=[],
            date="",
            body_text=(
                "Reference block below.\n\n"
                "From: Alice <employee@example.test>\n"
                "Sent: Monday, January 1, 2025 10:00 AM\n"
                "To: Bob <bob@example.com>\n"
                "Subject: Status"
            ),
            body_html="",
            folder="Inbox",
            has_attachments=False,
        )
        assert email.email_type == "original"
        assert "From: Alice <employee@example.test>" in email.clean_body

    def test_clean_body_strips_leading_forward_header_block_and_keeps_forwarded_content(self):
        email = Email(
            message_id="<m@test>",
            subject="FW: Status",
            sender_name="",
            sender_email="",
            to=[],
            cc=[],
            bcc=[],
            date="",
            body_text=(
                "From: Alice <employee@example.test>\n"
                "Sent: Monday, January 1, 2025 10:00 AM\n"
                "To: Bob <bob@example.com>\n"
                "Subject: Status\n\n"
                "Forwarded content starts here."
            ),
            body_html="",
            folder="Inbox",
            has_attachments=False,
        )
        assert email.clean_body == "Forwarded content starts here."

    def test_clean_body_strips_leading_forward_header_block_after_outlook_separator(self):
        email = Email(
            message_id="<m@test>",
            subject="FW: Status",
            sender_name="",
            sender_email="",
            to=[],
            cc=[],
            bcc=[],
            date="",
            body_text=(
                "________________________________\n"
                "From: Alice <employee@example.test>\n"
                "Sent: Monday, January 1, 2025 10:00 AM\n"
                "To: Bob <bob@example.com>\n"
                "Subject: Status\n\n"
                "Forwarded content starts here."
            ),
            body_html="",
            folder="Inbox",
            has_attachments=False,
        )
        assert email.clean_body == "Forwarded content starts here."


# ── German reply header stripping ─────────────────────────────


class TestCleanBodyGermanReplyHeaders:
    def test_clean_body_strips_german_reply_header_tail_before_persistence(self):
        email = Email(
            message_id="<m@test>",
            subject="AW: Status",
            sender_name="",
            sender_email="",
            to=[],
            cc=[],
            bcc=[],
            date="",
            body_text=(
                "Aktueller Stand unten.\n\n"
                "Von: Alice <employee@example.test>\n"
                "Gesendet: Montag, 1. Januar 2025 10:00\n"
                "An: Bob <bob@example.com>\n"
                "Betreff: Status"
            ),
            body_html="",
            folder="Inbox",
            has_attachments=False,
        )
        assert email.email_type == "reply"
        assert email.clean_body == "Aktueller Stand unten."
        assert email.body_normalization_version == BODY_NORMALIZATION_VERSION

    def test_clean_body_strips_reply_header_tail_after_signature_prelude(self):
        email = Email(
            message_id="<m@test>",
            subject="AW: Status",
            sender_name="",
            sender_email="",
            to=[],
            cc=[],
            bcc=[],
            date="",
            body_text=(
                "Aktueller Stand unten.\n\n"
                "Viele Grüße\nAlice\n\n"
                "Von: Bob <bob@example.com>\n"
                "Gesendet: Montag, 1. Januar 2025 10:00\n"
                "An: Alice <employee@example.test>\n"
                "Betreff: Status\n\n"
                "Vorheriger Inhalt."
            ),
            body_html="",
            folder="Inbox",
            has_attachments=False,
        )
        assert email.clean_body == "Aktueller Stand unten."

    def test_clean_body_strips_reply_header_tail_from_original_nachricht_separator(self):
        email = Email(
            message_id="<m@test>",
            subject="AW: Status",
            sender_name="",
            sender_email="",
            to=[],
            cc=[],
            bcc=[],
            date="",
            body_text=(
                "Danke, erledigt.\n\n"
                "Prof. Beispiel\n"
                "Leitung IT\n\n"
                "-----Original-Nachricht-----\n"
                "Von: Alice <employee@example.test>\n"
                "Gesendet: Montag, 1. Januar 2025 10:00\n"
                "An: Bob <bob@example.com>\n"
                "Betreff: Status\n\n"
                "Voriger Inhalt."
            ),
            body_html="",
            folder="Inbox",
            has_attachments=False,
        )
        assert email.clean_body == "Danke, erledigt.\n\nProf. Beispiel\nLeitung IT"

    def test_clean_body_strips_reply_header_tail_after_long_signature_prelude(self):
        email = Email(
            message_id="<m@test>",
            subject="RE: Status",
            sender_name="",
            sender_email="",
            to=[],
            cc=[],
            bcc=[],
            date="",
            body_text=(
                "Erledigt.\n\n"
                "Dr. employee\n"
                "Leitung IT\n"
                "Beispielweg 10\n"
                "12345 Musterstadt\n\n"
                "Von: Bob <bob@example.com>\n"
                "Gesendet: Montag, 1. Januar 2025 10:00\n"
                "An: Alice <employee@example.test>\n"
                "Betreff: Status\n\n"
                "Voriger Inhalt."
            ),
            body_html="",
            folder="Inbox",
            has_attachments=False,
        )
        assert email.clean_body == ("Erledigt.\n\nDr. employee\nLeitung IT\nBeispielweg 10\n12345 Musterstadt")

    def test_clean_body_keeps_german_headerish_tail_for_original_email(self):
        email = Email(
            message_id="<m@test>",
            subject="Archivnotiz",
            sender_name="",
            sender_email="",
            to=[],
            cc=[],
            bcc=[],
            date="",
            body_text=(
                "Referenzblock unten.\n\n"
                "Von: Alice <employee@example.test>\n"
                "Gesendet: Montag, 1. Januar 2025 10:00\n"
                "An: Bob <bob@example.com>\n"
                "Betreff: Status"
            ),
            body_html="",
            folder="Inbox",
            has_attachments=False,
        )
        assert email.email_type == "original"
        assert "Von: Alice <employee@example.test>" in email.clean_body


# ── Non-English reply header stripping (PT, PL) ──────────────


class TestCleanBodyNonEnglishReplyHeaders:
    def test_clean_body_strips_portuguese_reply_header_tail_before_persistence(self):
        email = Email(
            message_id="<m@test>",
            subject="RE: Status",
            sender_name="",
            sender_email="",
            to=[],
            cc=[],
            bcc=[],
            date="",
            body_text=(
                "Resposta atual.\n\n"
                "De: Alice <employee@example.test>\n"
                "Enviado: segunda-feira, 1 de janeiro de 2025 10:00\n"
                "Para: Bob <bob@example.com>\n"
                "Assunto: Status"
            ),
            body_html="",
            folder="Inbox",
            has_attachments=False,
        )
        assert email.email_type == "reply"
        assert email.clean_body == "Resposta atual."
        assert email.body_normalization_version == BODY_NORMALIZATION_VERSION

    def test_clean_body_strips_polish_reply_header_tail_before_persistence(self):
        email = Email(
            message_id="<m@test>",
            subject="RE: Status",
            sender_name="",
            sender_email="",
            to=[],
            cc=[],
            bcc=[],
            date="",
            body_text=(
                "Aktualna odpowiedz.\n\n"
                "Od: Alice <employee@example.test>\n"
                "Wyslano: poniedzialek, 1 stycznia 2025 10:00\n"
                "Do: Bob <bob@example.com>\n"
                "Temat: Status"
            ),
            body_html="",
            folder="Inbox",
            has_attachments=False,
        )
        assert email.email_type == "reply"
        assert email.clean_body == "Aktualna odpowiedz."
        assert email.body_normalization_version == BODY_NORMALIZATION_VERSION
