"use strict";

// This dataset is intentionally fictional. It is the entire data boundary for
// the Pages demo: the application does not read an archive or contact a service.
window.MailariumDemoData = {
  messages: [
    {
      id: "msg-harbor-01",
      subject: "RE: Harbor launch — moving the date",
      from: { name: "Maya Lindqvist", address: "maya.lindqvist@example.test" },
      to: ["omar.haddad@example.test", "ines.moreau@example.test"],
      date: "2026-05-14T09:42:00Z",
      folder: "Projects/Harbor",
      thread: "harbor-date",
      score: { semantic: 0.91, hybrid: 0.94, keyword: 0.88 },
      body: [
        "Omar, Inès —",
        "We are moving the Harbor launch to 9 June. The security review will not finish before 28 May, and I am not willing to ship the payment flow without its sign-off.",
        "Ken confirmed the vendor patch lands on 3 June. That leaves us four working days for regression, which is tight but honest.",
        "Please update the customer timeline today. I will brief the board on Thursday.",
        "Maya",
      ],
      quoted: [
        "On 13 May 2026, Omar Haddad wrote:",
        "Can we hold the 21 May date if we ship without the saved-cards feature?",
      ],
      attachments: ["harbor-launch-plan-v4.pdf", "regression-window.xlsx"],
    },
    {
      id: "msg-harbor-02",
      subject: "Harbor launch — can we hold 21 May?",
      from: { name: "Omar Haddad", address: "omar.haddad@example.test" },
      to: ["maya.lindqvist@example.test"],
      date: "2026-05-13T16:05:00Z",
      folder: "Projects/Harbor",
      thread: "harbor-date",
      score: { semantic: 0.86, hybrid: 0.89, keyword: 0.9 },
      body: [
        "Maya,",
        "Can we hold the 21 May date if we ship without the saved-cards feature? Sales has three customers waiting on the announcement.",
        "Omar",
      ],
      quoted: [],
      attachments: [],
    },
    {
      id: "msg-vendor-01",
      subject: "Patch schedule for the payment SDK",
      from: { name: "Ken Adeyemi", address: "ken.adeyemi@example.test" },
      to: ["maya.lindqvist@example.test", "lea.brandt@example.test"],
      date: "2026-05-12T11:20:00Z",
      folder: "Vendors/Payments",
      thread: "sdk",
      score: { semantic: 0.82, hybrid: 0.84, keyword: 0.71 },
      body: [
        "Hi Maya, Lea,",
        "The patch for the tokenisation issue is scheduled for 3 June. We cannot bring it forward without skipping our own certification step.",
        "Best,",
        "Ken",
      ],
      quoted: [],
      attachments: ["sdk-release-notes-3.8.2.txt"],
    },
    {
      id: "msg-security-01",
      subject: "Security review status — payment flow",
      from: { name: "Lea Brandt", address: "lea.brandt@example.test" },
      to: ["maya.lindqvist@example.test"],
      date: "2026-05-11T08:55:00Z",
      folder: "Projects/Harbor/Security",
      thread: "security",
      score: { semantic: 0.8, hybrid: 0.81, keyword: 0.74 },
      body: [
        "Maya,",
        "The review of the payment flow is two thirds done. The remaining items depend on the vendor patch; realistically we finish on 28 May at the earliest.",
        "Lea",
      ],
      quoted: [],
      attachments: [],
    },
    {
      id: "msg-harbor-03",
      subject: "Customer timeline draft",
      from: { name: "Inès Moreau-Castellanos", address: "ines.moreau@example.test" },
      to: ["maya.lindqvist@example.test", "omar.haddad@example.test"],
      date: "2026-05-15T13:30:00Z",
      folder: "Projects/Harbor",
      thread: "harbor-date",
      score: { semantic: 0.77, hybrid: 0.75, keyword: 0.69 },
      body: [
        "Draft wording for customers: “Harbor will be available from 9 June. We moved the date to complete an independent security review of the payment flow.”",
        "Comments by end of day, please.",
      ],
      quoted: [],
      attachments: [],
    },
    {
      id: "msg-sales-01",
      subject: "Fwd: Customer escalation — Northwind",
      from: { name: "Omar Haddad", address: "omar.haddad@example.test" },
      to: ["maya.lindqvist@example.test"],
      date: "2026-05-18T10:02:00Z",
      folder: "Sales",
      thread: "northwind",
      score: { semantic: 0.64, hybrid: 0.66, keyword: 0.58 },
      body: [
        "Forwarding Northwind's note. They are unhappy about the date but accept the reason. A call on Monday would help.",
      ],
      quoted: [],
      attachments: ["northwind-escalation.eml"],
    },
  ],
  findings: [
    {
      messageId: "msg-vendor-01",
      category: "dependency",
      quote: "The patch for the tokenisation issue is scheduled for 3 June.",
      summary: "The vendor patch date constrained when the security review could end.",
      relevance: 4,
    },
  ],
  overview: {
    monthlyVolume: [18, 24, 29, 35, 44, 72, 51, 39, 34, 28, 31, 37],
    labels: ["Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec", "Jan", "Feb", "Mar", "Apr", "May"],
  },
};
